[workspace]
resolver = "2"
members = [
    "pompeii",
    "pompeii-task",
    "bevy_pompeii",

    "examples",
]

[patch.crates-io]
#ash = { git = "https://github.com/icanwalkonwater/ash.git" }
#ash-window = { git = "https://github.com/icanwalkonwater/ash.git" }
