[package]
name = "pompeii"
version = "0.0.0"
authors = ["Lucas Malandrino <lucas.malandrino@gmail.com>"]
edition = "2021"
license = "LGPL-3.0-or-later"
description = "RESERVED for Vulkan renderer"
homepage = "https://github.com/icanwalkonwater/pompeii-rs"
repository = "https://github.com/icanwalkonwater/pompeii-rs"
readme = "../README.md"
keywords = []

[dependencies]
# pompeii-hal = { path = "../pompeii-hal", version = "*" }
